module.exports = {
  apps: [
    {
      name: 'tracer',
      script: 'npm',
      args: ['run', 'with-infisical', '--', 'npm', 'run', 'tracer'],
      wait_ready: true,
      listen_timeout: 5000,
    },
    {
      name: 'listener',
      script: 'npm',
      args: ['run', 'with-infisical', '--', 'npm', 'run', 'listener'],
      wait_ready: true,
      listen_timeout: 5000,
    },
    {
      name: 'workers',
      script: 'npm',
      args: ['run', 'with-infisical', '--', 'npm', 'run', 'workers'],
      wait_ready: true,
      listen_timeout: 5000,
    },
    {
      name: 'workers-bg',
      script: 'npm',
      args: [
        'run',
        'with-infisical',
        '--',
        'npm',
        'run',
        'workers',
        '--',
        '-m',
        'background',
      ],
      wait_ready: true,
      listen_timeout: 5000,
    },
    {
      name: 'account-webhooks',
      script: 'npm',
      args: [
        'run',
        'with-infisical',
        '--',
        'npm',
        'run',
        'account-webhooks',
        '--',
        '-c',
        'config.accounts.json',
      ],
    },
    {
      name: 'server_accounts',
      script: 'npm',
      args: [
        'run',
        'with-infisical',
        '--',
        'npm',
        'run',
        'serve',
        '--',
        '-p',
        '3001',
        '-c',
        'config.accounts.json',
        '-a',
      ],
      instances: 2,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'server',
      script: 'npm',
      args: [
        'run',
        'with-infisical',
        '--',
        'npm',
        'run',
        'serve',
        '--',
        '-p',
        '3000',
      ],
      instances: 2,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'renew-infisical-token',
      script: 'npm',
      args: [
        'run',
        'with-dotenv',
        '--',
        'bash',
        '-c',
        'npx @infisical/cli token renew $INFISICAL_TOKEN',
      ],
      // every day at midnight
      cron_restart: '0 0 * * *',
    },
  ],
}
